services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    K3n\Tonictypes\:
        resource: '../Classes/*'

    K3n\Tonictypes\Configuration\ConfigurationRegistry:
        public: true

    K3n\Tonictypes\Icon\TonictypesIconRegistry:
        public : true

    K3n\Tonictypes\Controller\Backend\AbstractBackendController:
        public : true

    K3n\Tonictypes\Controller\Backend\ClassController:
        public: true

    K3n\Tonictypes\Controller\Backend\TableController:
        public: true

    K3n\Tonictypes\Controller\Backend\EditDocumentController:
        public: true

    K3n\Tonictypes\Controller\Backend\QueryBuilderController:
        public: true

    K3n\Tonictypes\Controller\Backend\PredefinedDatatypeImportController:
        public: true

    K3n\Tonictypes\Controller\RecordController:
        public: true

    K3n\Tonictypes\Widgets\PredefinedDatatypeImportWidget:
        tags:
            - name: dashboard.widget
              identifier: 'tonictypes-predefined-datatype-import'
              groupNames: 'tonictypes'
              title: 'LLL:EXT:tonictypes/Resources/Private/Language/locallang.xlf:dashboard.predefined_datatype_import.title'
              description: 'LLL:EXT:tonictypes/Resources/Private/Language/locallang.xlf:dashboard.predefined_datatype_import.description'
              iconIdentifier: 'extensions-tonictypes-dashboard'
              height: 'medium'
              width: 'medium'

    K3n\Tonictypes\Form\Element\QueryBuilderElement:
        public: true
        autowire: false

    K3n\Tonictypes\Form\Element\UserElement:
        public: true
        autowire: false

    K3n\Tonictypes\Hooks\Constants:
        public: true

    K3n\Tonictypes\LabelUserFunc\Field:
        public: true

    K3n\Tonictypes\LabelUserFunc\Record:
        public: true

    K3n\Tonictypes\LabelUserFunc\Variable:
        public: true

    K3n\Tonictypes\UserFunc\Database:
        public: true

    K3n\Tonictypes\UserFunc\Datatype:
        public: true

    K3n\Tonictypes\UserFunc\Extension:
        public: true

    K3n\Tonictypes\UserFunc\Field:
        public: true

    K3n\Tonictypes\UserFunc\Icon:
        public: true

    K3n\Tonictypes\UserFunc\Logo:
        public: true

    K3n\Tonictypes\UserFunc\Record:
        public: true

    K3n\Tonictypes\UserFunc\Rte:
        public: true

    K3n\Tonictypes\UserFunc\Template:
        public: true

    K3n\Tonictypes\UserFunc\Text:
        public: true

    K3n\Tonictypes\UserFunc\Variable:
        public: true

    K3n\Tonictypes\Database\EventListener\TonictypesDynamicTableSchemaListener:
        tags:
            - name: event.listener
              identifier: 'tonictypes/dynamic-table-schema-listener'
              event: TYPO3\CMS\Core\Database\Event\AlterTableDefinitionStatementsEvent

    K3n\Tonictypes\EventListener\ModifyLoadedPageTsConfigEventListener:
        tags:
            - name: event.listener
              identifier: 'tonictypes/modify-loaded-page-tsconfig'
              event: TYPO3\CMS\Core\TypoScript\IncludeTree\Event\ModifyLoadedPageTsConfigEvent

    K3n\Tonictypes\EventListener\NewContentElementPreviewRenderer:
        tags:
            - name: event.listener
              identifier: 'tonictypes/preview-renderer'
              event: TYPO3\CMS\Backend\View\Event\PageContentPreviewRenderingEvent
              priority: 100

    K3n\Tonictypes\EventListener\RegisterDatatypeIconsOnBootCompleted:
      tags:
        - name: event.listener
          identifier: 'tonictypes/register-datatype-icons-on-boot-completed'
          event: TYPO3\CMS\Core\Core\Event\BootCompletedEvent